class_name GroundData

enum GROUND_TYPES {
	GRASS,
	DIRT,
	SAND,
	CONCRETE,
}

const GROUND_COLOURS: Dictionary[GROUND_TYPES, Color] = {
	GROUND_TYPES.GRASS : Color.DARK_GREEN,
	GROUND_TYPES.DIRT : Color.SADDLE_BROWN,
	GROUND_TYPES.SAND : Color.BURLYWOOD,
	GROUND_TYPES.CONCRETE : Color.GRAY,
}
